# find Qt folder and add it to cmake search path, cannot use function() due to CMAKE_PREFIX_PATH will be a local variable
macro(FindAddQtPath QtPaths)
    foreach (r ${ARGV})
        file(GLOB FOLDER RELATIVE ${r} ${r}/*)
        foreach (f ${FOLDER})
            if (IS_DIRECTORY ${r}/${f} AND ${f} MATCHES "Qt[0-9.]+")
                string(SUBSTRING ${f} 2 -1 QtVersion)
                message(STATUS "Found Qt ${QtVersion} in ${r}/${f}")
                if (UNIX)
                    set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH};${r}/${f}/${QtVersion}/gcc_64/lib/cmake")
                elseif (WIN32)
                    set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH};${r}/${f}/${QtVersion}/msvc2017_64/lib/cmake")
                endif ()
                break()
            endif ()
        endforeach ()
    endforeach ()
endmacro()